#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LookTarget

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LookTarget.BP_LookTarget_C
// 0x0010 (0x0230 - 0x0220)
class ABP_LookTarget_C final : public AActor
{
public:
	class USceneComponent*                        LookTarget;                                        // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LookTarget_C">();
	}
	static class ABP_LookTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LookTarget_C>();
	}
};
static_assert(alignof(ABP_LookTarget_C) == 0x000008, "Wrong alignment on ABP_LookTarget_C");
static_assert(sizeof(ABP_LookTarget_C) == 0x000230, "Wrong size on ABP_LookTarget_C");
static_assert(offsetof(ABP_LookTarget_C, LookTarget) == 0x000220, "Member 'ABP_LookTarget_C::LookTarget' has a wrong offset!");
static_assert(offsetof(ABP_LookTarget_C, Arrow) == 0x000228, "Member 'ABP_LookTarget_C::Arrow' has a wrong offset!");

}

