#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RCSingletonObject

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RCSingletonObject.BP_RCSingletonObject_C
// 0x0000 (0x0048 - 0x0048)
class UBP_RCSingletonObject_C final : public URCSingletonObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_RCSingletonObject_C">();
	}
	static class UBP_RCSingletonObject_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RCSingletonObject_C>();
	}
};
static_assert(alignof(UBP_RCSingletonObject_C) == 0x000008, "Wrong alignment on UBP_RCSingletonObject_C");
static_assert(sizeof(UBP_RCSingletonObject_C) == 0x000048, "Wrong size on UBP_RCSingletonObject_C");

}

