#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UI_IconRow

#include "Basic.hpp"

#include "SpRuntime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_UI_IconRow.BP_UI_IconRow_C
// 0x0000 (0x01B8 - 0x01B8)
class UBP_UI_IconRow_C final : public USpUIRichTextIcon
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_UI_IconRow_C">();
	}
	static class UBP_UI_IconRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_UI_IconRow_C>();
	}
};
static_assert(alignof(UBP_UI_IconRow_C) == 0x000008, "Wrong alignment on UBP_UI_IconRow_C");
static_assert(sizeof(UBP_UI_IconRow_C) == 0x0001B8, "Wrong size on UBP_UI_IconRow_C");

}

