#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MovieBP

#include "Basic.hpp"

#include "MovieBP_classes.hpp"
#include "MovieBP_parameters.hpp"


namespace SDK
{

// Function MovieBP.MovieBP_C.ExecuteUbergraph_MovieBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMovieBP_C::ExecuteUbergraph_MovieBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "ExecuteUbergraph_MovieBP");

	Params::MovieBP_C_ExecuteUbergraph_MovieBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MovieBP.MovieBP_C.OnStartLoadEvent
// (BlueprintCallable, BlueprintEvent)

void AMovieBP_C::OnStartLoadEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "OnStartLoadEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MovieBP.MovieBP_C.PlayMovie_Event
// (BlueprintCallable, BlueprintEvent)

void AMovieBP_C::PlayMovie_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "PlayMovie_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MovieBP.MovieBP_C.OnFinishedEvent_イベント_0
// (BlueprintCallable, BlueprintEvent)

void AMovieBP_C::OnFinishedEvent______________0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "OnFinishedEvent_イベント_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MovieBP.MovieBP_C.OnLoadedEvent_イベント_0
// (BlueprintCallable, BlueprintEvent)

void AMovieBP_C::OnLoadedEvent______________0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "OnLoadedEvent_イベント_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MovieBP.MovieBP_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMovieBP_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "ReceiveTick");

	Params::MovieBP_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MovieBP.MovieBP_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AMovieBP_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MovieBP.MovieBP_C.動画読み込み処理
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           MovieID_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void AMovieBP_C::m________________________0(const class FString& MovieID_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "動画読み込み処理");

	Params::MovieBP_C_m________________________0 Parms{};

	Parms.MovieID_0 = std::move(MovieID_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MovieBP.MovieBP_C.動画再生処理
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SubTitleID_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AMovieBP_C::m_________________(class FName SubTitleID_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "動画再生処理");

	Params::MovieBP_C_m_________________ Parms{};

	Parms.SubTitleID_0 = SubTitleID_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MovieBP.MovieBP_C.動画が終了したか
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   MovieIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    isFinish                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AMovieBP_C::m_______________________(int32 MovieIndex, bool* isFinish)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MovieBP_C", "動画が終了したか");

	Params::MovieBP_C_m_______________________ Parms{};

	Parms.MovieIndex = MovieIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (isFinish != nullptr)
		*isFinish = Parms.isFinish;
}

}

