#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PositioningMode

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum PositioningMode.PositioningMode
// NumValues: 0x0005
enum class EPositioningMode : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	PositioningMode_MAX                      = 4,
};

}

