#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RCTPSCameraCore_BP_Main

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RCTPSCameraCore_BP_Main.RCTPSCameraCore_BP_Main_C
// 0x0010 (0x0960 - 0x0950)
class ARCTPSCameraCore_BP_Main_C final : public ARCTPSCamera
{
public:
	class USphereComponent*                       Sphere;                                            // 0x0950(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RCTPSCameraCore_BP_Main_C">();
	}
	static class ARCTPSCameraCore_BP_Main_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARCTPSCameraCore_BP_Main_C>();
	}
};
static_assert(alignof(ARCTPSCameraCore_BP_Main_C) == 0x000010, "Wrong alignment on ARCTPSCameraCore_BP_Main_C");
static_assert(sizeof(ARCTPSCameraCore_BP_Main_C) == 0x000960, "Wrong size on ARCTPSCameraCore_BP_Main_C");
static_assert(offsetof(ARCTPSCameraCore_BP_Main_C, Sphere) == 0x000950, "Member 'ARCTPSCameraCore_BP_Main_C::Sphere' has a wrong offset!");

}

