#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RCTPSCameraCore_In_00

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RCTPSCameraCore_In_00.RCTPSCameraCore_In_00_C
// 0x0010 (0x0960 - 0x0950)
class ARCTPSCameraCore_In_00_C final : public ARCTPSCamera
{
public:
	class USphereComponent*                       Sphere;                                            // 0x0950(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RCTPSCameraCore_In_00_C">();
	}
	static class ARCTPSCameraCore_In_00_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARCTPSCameraCore_In_00_C>();
	}
};
static_assert(alignof(ARCTPSCameraCore_In_00_C) == 0x000010, "Wrong alignment on ARCTPSCameraCore_In_00_C");
static_assert(sizeof(ARCTPSCameraCore_In_00_C) == 0x000960, "Wrong size on ARCTPSCameraCore_In_00_C");
static_assert(offsetof(ARCTPSCameraCore_In_00_C, Sphere) == 0x000950, "Member 'ARCTPSCameraCore_In_00_C::Sphere' has a wrong offset!");

}

