#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReTalk_NamePL

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_ReTalk_NamePL.WBP_ReTalk_NamePL_C.ExecuteUbergraph_WBP_ReTalk_NamePL
// 0x0004 (0x0004 - 0x0000)
struct WBP_ReTalk_NamePL_C_ExecuteUbergraph_WBP_ReTalk_NamePL final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ReTalk_NamePL_C_ExecuteUbergraph_WBP_ReTalk_NamePL) == 0x000004, "Wrong alignment on WBP_ReTalk_NamePL_C_ExecuteUbergraph_WBP_ReTalk_NamePL");
static_assert(sizeof(WBP_ReTalk_NamePL_C_ExecuteUbergraph_WBP_ReTalk_NamePL) == 0x000004, "Wrong size on WBP_ReTalk_NamePL_C_ExecuteUbergraph_WBP_ReTalk_NamePL");
static_assert(offsetof(WBP_ReTalk_NamePL_C_ExecuteUbergraph_WBP_ReTalk_NamePL, EntryPoint) == 0x000000, "Member 'WBP_ReTalk_NamePL_C_ExecuteUbergraph_WBP_ReTalk_NamePL::EntryPoint' has a wrong offset!");

}

