#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_NzSkill_SetIcon_Equip

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_NzSkill_SetIcon_Equip.WBP_Menu_NzSkill_SetIcon_Equip_C
// 0x0008 (0x02F0 - 0x02E8)
class UWBP_Menu_NzSkill_SetIcon_Equip_C final : public URCUiMenuCommonIcon
{
public:
	class UImage*                                 Image_0;                                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_NzSkill_SetIcon_Equip_C">();
	}
	static class UWBP_Menu_NzSkill_SetIcon_Equip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_NzSkill_SetIcon_Equip_C>();
	}
};
static_assert(alignof(UWBP_Menu_NzSkill_SetIcon_Equip_C) == 0x000008, "Wrong alignment on UWBP_Menu_NzSkill_SetIcon_Equip_C");
static_assert(sizeof(UWBP_Menu_NzSkill_SetIcon_Equip_C) == 0x0002F0, "Wrong size on UWBP_Menu_NzSkill_SetIcon_Equip_C");
static_assert(offsetof(UWBP_Menu_NzSkill_SetIcon_Equip_C, Image_0) == 0x0002E8, "Member 'UWBP_Menu_NzSkill_SetIcon_Equip_C::Image_0' has a wrong offset!");

}

