#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AreaMap_Guide

#include "Basic.hpp"

#include "WBP_AreaMap_Guide_classes.hpp"
#include "WBP_AreaMap_Guide_parameters.hpp"


namespace SDK
{

// Function WBP_AreaMap_Guide.WBP_AreaMap_Guide_C.SetTextID
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FName>                     TextID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TArray<class URichTextBlock*>           TextBlock                                              (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UWBP_AreaMap_Guide_C::SetTextID(TArray<class FName>& TextID, TArray<class URichTextBlock*>& TextBlock)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AreaMap_Guide_C", "SetTextID");

	Params::WBP_AreaMap_Guide_C_SetTextID Parms{};

	Parms.TextID = std::move(TextID);
	Parms.TextBlock = std::move(TextBlock);

	UObject::ProcessEvent(Func, &Parms);

	TextID = std::move(Parms.TextID);
	TextBlock = std::move(Parms.TextBlock);
}


// Function WBP_AreaMap_Guide.WBP_AreaMap_Guide_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_AreaMap_Guide_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AreaMap_Guide_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_AreaMap_Guide.WBP_AreaMap_Guide_C.ExecuteUbergraph_WBP_AreaMap_Guide
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_AreaMap_Guide_C::ExecuteUbergraph_WBP_AreaMap_Guide(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_AreaMap_Guide_C", "ExecuteUbergraph_WBP_AreaMap_Guide");

	Params::WBP_AreaMap_Guide_C_ExecuteUbergraph_WBP_AreaMap_Guide Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

