#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Title_ChapterSelect_Caption

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Title_ChapterSelect_Caption.WBP_Title_ChapterSelect_Caption_C
// 0x0008 (0x02F0 - 0x02E8)
class UWBP_Title_ChapterSelect_Caption_C final : public URCTitleChapterSelectCaption
{
public:
	class UImage*                                 Caption_Pl;                                        // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Title_ChapterSelect_Caption_C">();
	}
	static class UWBP_Title_ChapterSelect_Caption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Title_ChapterSelect_Caption_C>();
	}
};
static_assert(alignof(UWBP_Title_ChapterSelect_Caption_C) == 0x000008, "Wrong alignment on UWBP_Title_ChapterSelect_Caption_C");
static_assert(sizeof(UWBP_Title_ChapterSelect_Caption_C) == 0x0002F0, "Wrong size on UWBP_Title_ChapterSelect_Caption_C");
static_assert(offsetof(UWBP_Title_ChapterSelect_Caption_C, Caption_Pl) == 0x0002E8, "Member 'UWBP_Title_ChapterSelect_Caption_C::Caption_Pl' has a wrong offset!");

}

