#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Title_Language

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Title_Language.WBP_Title_Language_C
// 0x0010 (0x0320 - 0x0310)
class UWBP_Title_Language_C final : public URCTitleLanguage
{
public:
	class UWBP_Title_Language_Window_C*           Language_Window;                                   // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Title_Help_C*                      Title_Help;                                        // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Title_Language_C">();
	}
	static class UWBP_Title_Language_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Title_Language_C>();
	}
};
static_assert(alignof(UWBP_Title_Language_C) == 0x000008, "Wrong alignment on UWBP_Title_Language_C");
static_assert(sizeof(UWBP_Title_Language_C) == 0x000320, "Wrong size on UWBP_Title_Language_C");
static_assert(offsetof(UWBP_Title_Language_C, Language_Window) == 0x000310, "Member 'UWBP_Title_Language_C::Language_Window' has a wrong offset!");
static_assert(offsetof(UWBP_Title_Language_C, Title_Help) == 0x000318, "Member 'UWBP_Title_Language_C::Title_Help' has a wrong offset!");

}

