#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Int_Talk_Base_On

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Int_Talk_Base_On.WBP_Int_Talk_Base_On_C
// 0x0008 (0x0318 - 0x0310)
class UWBP_Int_Talk_Base_On_C final : public URCUiInteractTalkOn
{
public:
	class UImage*                                 Talk_Base_On;                                      // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Int_Talk_Base_On_C">();
	}
	static class UWBP_Int_Talk_Base_On_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Int_Talk_Base_On_C>();
	}
};
static_assert(alignof(UWBP_Int_Talk_Base_On_C) == 0x000008, "Wrong alignment on UWBP_Int_Talk_Base_On_C");
static_assert(sizeof(UWBP_Int_Talk_Base_On_C) == 0x000318, "Wrong size on UWBP_Int_Talk_Base_On_C");
static_assert(offsetof(UWBP_Int_Talk_Base_On_C, Talk_Base_On) == 0x000310, "Member 'UWBP_Int_Talk_Base_On_C::Talk_Base_On' has a wrong offset!");

}

