#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Gallery_ImageTitleName

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Gallery_ImageTitleName.WBP_Gallery_ImageTitleName_C
// 0x0010 (0x0328 - 0x0318)
class UWBP_Gallery_ImageTitleName_C final : public URCTitleGalleryMovieImageName
{
public:
	class UImage*                                 Gallery_Headline_Base;                             // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Gallery_Headline_Base_1;                           // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Gallery_ImageTitleName_C">();
	}
	static class UWBP_Gallery_ImageTitleName_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Gallery_ImageTitleName_C>();
	}
};
static_assert(alignof(UWBP_Gallery_ImageTitleName_C) == 0x000008, "Wrong alignment on UWBP_Gallery_ImageTitleName_C");
static_assert(sizeof(UWBP_Gallery_ImageTitleName_C) == 0x000328, "Wrong size on UWBP_Gallery_ImageTitleName_C");
static_assert(offsetof(UWBP_Gallery_ImageTitleName_C, Gallery_Headline_Base) == 0x000318, "Member 'UWBP_Gallery_ImageTitleName_C::Gallery_Headline_Base' has a wrong offset!");
static_assert(offsetof(UWBP_Gallery_ImageTitleName_C, Gallery_Headline_Base_1) == 0x000320, "Member 'UWBP_Gallery_ImageTitleName_C::Gallery_Headline_Base_1' has a wrong offset!");

}

