#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_SaveLoad_Select

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_SaveLoad_Select.WBP_Menu_SaveLoad_Select_C
// 0x0000 (0x0350 - 0x0350)
class UWBP_Menu_SaveLoad_Select_C final : public URCSaveLoadSelect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_SaveLoad_Select_C">();
	}
	static class UWBP_Menu_SaveLoad_Select_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_SaveLoad_Select_C>();
	}
};
static_assert(alignof(UWBP_Menu_SaveLoad_Select_C) == 0x000008, "Wrong alignment on UWBP_Menu_SaveLoad_Select_C");
static_assert(sizeof(UWBP_Menu_SaveLoad_Select_C) == 0x000350, "Wrong size on UWBP_Menu_SaveLoad_Select_C");

}

