#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Chos_TargetName_re

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Chos_TargetName_re.WBP_Chos_TargetName_re_C
// 0x0000 (0x0358 - 0x0358)
class UWBP_Chos_TargetName_re_C final : public URCReUiChousaTargetName
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Chos_TargetName_re_C">();
	}
	static class UWBP_Chos_TargetName_re_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Chos_TargetName_re_C>();
	}
};
static_assert(alignof(UWBP_Chos_TargetName_re_C) == 0x000008, "Wrong alignment on UWBP_Chos_TargetName_re_C");
static_assert(sizeof(UWBP_Chos_TargetName_re_C) == 0x000358, "Wrong size on UWBP_Chos_TargetName_re_C");

}

