#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReTalk_Cursor

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_ReTalk_Cursor.WBP_ReTalk_Cursor_C.ExecuteUbergraph_WBP_ReTalk_Cursor
// 0x0004 (0x0004 - 0x0000)
struct WBP_ReTalk_Cursor_C_ExecuteUbergraph_WBP_ReTalk_Cursor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_ReTalk_Cursor_C_ExecuteUbergraph_WBP_ReTalk_Cursor) == 0x000004, "Wrong alignment on WBP_ReTalk_Cursor_C_ExecuteUbergraph_WBP_ReTalk_Cursor");
static_assert(sizeof(WBP_ReTalk_Cursor_C_ExecuteUbergraph_WBP_ReTalk_Cursor) == 0x000004, "Wrong size on WBP_ReTalk_Cursor_C_ExecuteUbergraph_WBP_ReTalk_Cursor");
static_assert(offsetof(WBP_ReTalk_Cursor_C_ExecuteUbergraph_WBP_ReTalk_Cursor, EntryPoint) == 0x000000, "Member 'WBP_ReTalk_Cursor_C_ExecuteUbergraph_WBP_ReTalk_Cursor::EntryPoint' has a wrong offset!");

}

