#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_SvLd_Select_Btn_Load_Def

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_SvLd_Select_Btn_Load_Def.WBP_Menu_SvLd_Select_Btn_Load_Def_C
// 0x0010 (0x0280 - 0x0270)
class UWBP_Menu_SvLd_Select_Btn_Load_Def_C final : public UUserWidget
{
public:
	class UImage*                                 Text_Base_Def;                                     // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Text_Load_Def;                                     // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_SvLd_Select_Btn_Load_Def_C">();
	}
	static class UWBP_Menu_SvLd_Select_Btn_Load_Def_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_SvLd_Select_Btn_Load_Def_C>();
	}
};
static_assert(alignof(UWBP_Menu_SvLd_Select_Btn_Load_Def_C) == 0x000008, "Wrong alignment on UWBP_Menu_SvLd_Select_Btn_Load_Def_C");
static_assert(sizeof(UWBP_Menu_SvLd_Select_Btn_Load_Def_C) == 0x000280, "Wrong size on UWBP_Menu_SvLd_Select_Btn_Load_Def_C");
static_assert(offsetof(UWBP_Menu_SvLd_Select_Btn_Load_Def_C, Text_Base_Def) == 0x000270, "Member 'UWBP_Menu_SvLd_Select_Btn_Load_Def_C::Text_Base_Def' has a wrong offset!");
static_assert(offsetof(UWBP_Menu_SvLd_Select_Btn_Load_Def_C, Text_Load_Def) == 0x000278, "Member 'UWBP_Menu_SvLd_Select_Btn_Load_Def_C::Text_Load_Def' has a wrong offset!");

}

