#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Collect_Figure

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_Collect_Figure.WBP_Menu_Collect_Figure_C
// 0x0008 (0x0290 - 0x0288)
class UWBP_Menu_Collect_Figure_C final : public URCMenuCollectionFigure
{
public:
	class UImage*                                 Figure_Bg_Ure;                                     // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_Collect_Figure_C">();
	}
	static class UWBP_Menu_Collect_Figure_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_Collect_Figure_C>();
	}
};
static_assert(alignof(UWBP_Menu_Collect_Figure_C) == 0x000008, "Wrong alignment on UWBP_Menu_Collect_Figure_C");
static_assert(sizeof(UWBP_Menu_Collect_Figure_C) == 0x000290, "Wrong size on UWBP_Menu_Collect_Figure_C");
static_assert(offsetof(UWBP_Menu_Collect_Figure_C, Figure_Bg_Ure) == 0x000288, "Member 'UWBP_Menu_Collect_Figure_C::Figure_Bg_Ure' has a wrong offset!");

}

