#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReSelectEyeTracking

#include "Basic.hpp"

#include "WBP_ReSelectEyeTracking_classes.hpp"
#include "WBP_ReSelectEyeTracking_parameters.hpp"


namespace SDK
{

// Function WBP_ReSelectEyeTracking.WBP_ReSelectEyeTracking_C.ExecuteUbergraph_WBP_ReSelectEyeTracking
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReSelectEyeTracking_C::ExecuteUbergraph_WBP_ReSelectEyeTracking(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEyeTracking_C", "ExecuteUbergraph_WBP_ReSelectEyeTracking");

	Params::WBP_ReSelectEyeTracking_C_ExecuteUbergraph_WBP_ReSelectEyeTracking Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReSelectEyeTracking.WBP_ReSelectEyeTracking_C.OnHideStarted
// (Event, Public, BlueprintEvent)

void UWBP_ReSelectEyeTracking_C::OnHideStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEyeTracking_C", "OnHideStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReSelectEyeTracking.WBP_ReSelectEyeTracking_C.OnShowStarted
// (Event, Public, BlueprintEvent)

void UWBP_ReSelectEyeTracking_C::OnShowStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEyeTracking_C", "OnShowStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReSelectEyeTracking.WBP_ReSelectEyeTracking_C.CustomNavigation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_ReSelectEyeTracking_C::CustomNavigation(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEyeTracking_C", "CustomNavigation");

	Params::WBP_ReSelectEyeTracking_C_CustomNavigation Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

