#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ShortLoading

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_ShortLoading.WBP_ShortLoading_C
// 0x0008 (0x0308 - 0x0300)
class UWBP_ShortLoading_C final : public URCUiShortLoadingIcon
{
public:
	class UImage*                                 Img_Loading_Icon;                                  // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_ShortLoading_C">();
	}
	static class UWBP_ShortLoading_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_ShortLoading_C>();
	}
};
static_assert(alignof(UWBP_ShortLoading_C) == 0x000008, "Wrong alignment on UWBP_ShortLoading_C");
static_assert(sizeof(UWBP_ShortLoading_C) == 0x000308, "Wrong size on UWBP_ShortLoading_C");
static_assert(offsetof(UWBP_ShortLoading_C, Img_Loading_Icon) == 0x000300, "Member 'UWBP_ShortLoading_C::Img_Loading_Icon' has a wrong offset!");

}

