#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReTalk_Cursor_Circle

#include "Basic.hpp"

#include "WBP_ReTalk_Cursor_Circle_classes.hpp"
#include "WBP_ReTalk_Cursor_Circle_parameters.hpp"


namespace SDK
{

// Function WBP_ReTalk_Cursor_Circle.WBP_ReTalk_Cursor_Circle_C.ExecuteUbergraph_WBP_ReTalk_Cursor_Circle
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReTalk_Cursor_Circle_C::ExecuteUbergraph_WBP_ReTalk_Cursor_Circle(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReTalk_Cursor_Circle_C", "ExecuteUbergraph_WBP_ReTalk_Cursor_Circle");

	Params::WBP_ReTalk_Cursor_Circle_C_ExecuteUbergraph_WBP_ReTalk_Cursor_Circle Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReTalk_Cursor_Circle.WBP_ReTalk_Cursor_Circle_C.OnHideStarted
// (Event, Public, BlueprintEvent)

void UWBP_ReTalk_Cursor_Circle_C::OnHideStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReTalk_Cursor_Circle_C", "OnHideStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReTalk_Cursor_Circle.WBP_ReTalk_Cursor_Circle_C.OnShowStarted
// (Event, Public, BlueprintEvent)

void UWBP_ReTalk_Cursor_Circle_C::OnShowStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReTalk_Cursor_Circle_C", "OnShowStarted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReTalk_Cursor_Circle.WBP_ReTalk_Cursor_Circle_C.OnShowFinished
// (Event, Public, BlueprintEvent)

void UWBP_ReTalk_Cursor_Circle_C::OnShowFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReTalk_Cursor_Circle_C", "OnShowFinished");

	UObject::ProcessEvent(Func, nullptr);
}

}

