#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Collect_Icon_Kidoku

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_Collect_Icon_Kidoku.WBP_Menu_Collect_Icon_Kidoku_C
// 0x0008 (0x02A0 - 0x0298)
class UWBP_Menu_Collect_Icon_Kidoku_C final : public URCMenuCollectionCheckIcon
{
public:
	class UImage*                                 Icon_Kidoku_Flame;                                 // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_Collect_Icon_Kidoku_C">();
	}
	static class UWBP_Menu_Collect_Icon_Kidoku_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_Collect_Icon_Kidoku_C>();
	}
};
static_assert(alignof(UWBP_Menu_Collect_Icon_Kidoku_C) == 0x000008, "Wrong alignment on UWBP_Menu_Collect_Icon_Kidoku_C");
static_assert(sizeof(UWBP_Menu_Collect_Icon_Kidoku_C) == 0x0002A0, "Wrong size on UWBP_Menu_Collect_Icon_Kidoku_C");
static_assert(offsetof(UWBP_Menu_Collect_Icon_Kidoku_C, Icon_Kidoku_Flame) == 0x000298, "Member 'UWBP_Menu_Collect_Icon_Kidoku_C::Icon_Kidoku_Flame' has a wrong offset!");

}

