#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_KagiSelect_Image

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_KagiSelect_Image.WBP_Menu_KagiSelect_Image_C
// 0x0010 (0x0320 - 0x0310)
class UWBP_Menu_KagiSelect_Image_C final : public URCUiMenuKagiImage
{
public:
	class UImage*                                 Image_3;                                           // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Kagi_Image_Dummy_000;                              // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_KagiSelect_Image_C">();
	}
	static class UWBP_Menu_KagiSelect_Image_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_KagiSelect_Image_C>();
	}
};
static_assert(alignof(UWBP_Menu_KagiSelect_Image_C) == 0x000008, "Wrong alignment on UWBP_Menu_KagiSelect_Image_C");
static_assert(sizeof(UWBP_Menu_KagiSelect_Image_C) == 0x000320, "Wrong size on UWBP_Menu_KagiSelect_Image_C");
static_assert(offsetof(UWBP_Menu_KagiSelect_Image_C, Image_3) == 0x000310, "Member 'UWBP_Menu_KagiSelect_Image_C::Image_3' has a wrong offset!");
static_assert(offsetof(UWBP_Menu_KagiSelect_Image_C, Kagi_Image_Dummy_000) == 0x000318, "Member 'UWBP_Menu_KagiSelect_Image_C::Kagi_Image_Dummy_000' has a wrong offset!");

}

