#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Collect_Hint

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_Collect_Hint.WBP_Menu_Collect_Hint_C
// 0x0000 (0x0398 - 0x0398)
class UWBP_Menu_Collect_Hint_C final : public URCMenuCollectionHint
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_Collect_Hint_C">();
	}
	static class UWBP_Menu_Collect_Hint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_Collect_Hint_C>();
	}
};
static_assert(alignof(UWBP_Menu_Collect_Hint_C) == 0x000008, "Wrong alignment on UWBP_Menu_Collect_Hint_C");
static_assert(sizeof(UWBP_Menu_Collect_Hint_C) == 0x000398, "Wrong size on UWBP_Menu_Collect_Hint_C");

}

