#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Title_TitleMenu_List_Item

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Title_TitleMenu_List_Item.WBP_Title_TitleMenu_List_Item_C
// 0x0008 (0x0358 - 0x0350)
class UWBP_Title_TitleMenu_List_Item_C final : public URCTitleMenuListItem
{
public:
	class UWidgetSwitcher*                        Switcher_ListItem;                                 // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Title_TitleMenu_List_Item_C">();
	}
	static class UWBP_Title_TitleMenu_List_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Title_TitleMenu_List_Item_C>();
	}
};
static_assert(alignof(UWBP_Title_TitleMenu_List_Item_C) == 0x000008, "Wrong alignment on UWBP_Title_TitleMenu_List_Item_C");
static_assert(sizeof(UWBP_Title_TitleMenu_List_Item_C) == 0x000358, "Wrong size on UWBP_Title_TitleMenu_List_Item_C");
static_assert(offsetof(UWBP_Title_TitleMenu_List_Item_C, Switcher_ListItem) == 0x000350, "Member 'UWBP_Title_TitleMenu_List_Item_C::Switcher_ListItem' has a wrong offset!");

}

