#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Nag_Message

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Nag_Message.WBP_Nag_Message_C
// 0x0008 (0x0378 - 0x0370)
class UWBP_Nag_Message_C final : public URCUiSubtitle
{
public:
	class UWBP_ReTalk_Cursor_C*                   ReTalk_Cursor;                                     // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Nag_Message_C">();
	}
	static class UWBP_Nag_Message_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Nag_Message_C>();
	}
};
static_assert(alignof(UWBP_Nag_Message_C) == 0x000008, "Wrong alignment on UWBP_Nag_Message_C");
static_assert(sizeof(UWBP_Nag_Message_C) == 0x000378, "Wrong size on UWBP_Nag_Message_C");
static_assert(offsetof(UWBP_Nag_Message_C, ReTalk_Cursor) == 0x000370, "Member 'UWBP_Nag_Message_C::ReTalk_Cursor' has a wrong offset!");

}

