#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Quest_ListIcon_Close

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_Quest_ListIcon_Close.WBP_Menu_Quest_ListIcon_Close_C
// 0x0008 (0x0278 - 0x0270)
class UWBP_Menu_Quest_ListIcon_Close_C final : public UUserWidget
{
public:
	class UImage*                                 ListIcon_Close;                                    // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_Quest_ListIcon_Close_C">();
	}
	static class UWBP_Menu_Quest_ListIcon_Close_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_Quest_ListIcon_Close_C>();
	}
};
static_assert(alignof(UWBP_Menu_Quest_ListIcon_Close_C) == 0x000008, "Wrong alignment on UWBP_Menu_Quest_ListIcon_Close_C");
static_assert(sizeof(UWBP_Menu_Quest_ListIcon_Close_C) == 0x000278, "Wrong size on UWBP_Menu_Quest_ListIcon_Close_C");
static_assert(offsetof(UWBP_Menu_Quest_ListIcon_Close_C, ListIcon_Close) == 0x000270, "Member 'UWBP_Menu_Quest_ListIcon_Close_C::ListIcon_Close' has a wrong offset!");

}

