#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Collection_Window

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_Collection_Window.WBP_Menu_Collection_Window_C
// 0x0000 (0x0348 - 0x0348)
class UWBP_Menu_Collection_Window_C final : public URCMenuCollectionWindow
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_Collection_Window_C">();
	}
	static class UWBP_Menu_Collection_Window_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_Collection_Window_C>();
	}
};
static_assert(alignof(UWBP_Menu_Collection_Window_C) == 0x000008, "Wrong alignment on UWBP_Menu_Collection_Window_C");
static_assert(sizeof(UWBP_Menu_Collection_Window_C) == 0x000348, "Wrong size on UWBP_Menu_Collection_Window_C");

}

