#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_AdjustWindow_BTN_Parts

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_AdjustWindow_BTN_Parts.WBP_AdjustWindow_BTN_Parts_C
// 0x0010 (0x0350 - 0x0340)
class UWBP_AdjustWindow_BTN_Parts_C final : public URCUiGenericButtonParts
{
public:
	class UImage*                                 Img_Base;                                          // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Img_Flame_On;                                      // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_AdjustWindow_BTN_Parts_C">();
	}
	static class UWBP_AdjustWindow_BTN_Parts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_AdjustWindow_BTN_Parts_C>();
	}
};
static_assert(alignof(UWBP_AdjustWindow_BTN_Parts_C) == 0x000008, "Wrong alignment on UWBP_AdjustWindow_BTN_Parts_C");
static_assert(sizeof(UWBP_AdjustWindow_BTN_Parts_C) == 0x000350, "Wrong size on UWBP_AdjustWindow_BTN_Parts_C");
static_assert(offsetof(UWBP_AdjustWindow_BTN_Parts_C, Img_Base) == 0x000340, "Member 'UWBP_AdjustWindow_BTN_Parts_C::Img_Base' has a wrong offset!");
static_assert(offsetof(UWBP_AdjustWindow_BTN_Parts_C, Img_Flame_On) == 0x000348, "Member 'UWBP_AdjustWindow_BTN_Parts_C::Img_Flame_On' has a wrong offset!");

}

