#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_NzSkill_Icon_Equip

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_NzSkill_Icon_Equip.WBP_Menu_NzSkill_Icon_Equip_C
// 0x0008 (0x0300 - 0x02F8)
class UWBP_Menu_NzSkill_Icon_Equip_C final : public URCUiMenuSkillTreeIconEffect
{
public:
	class UImage*                                 Icon_Equip;                                        // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_NzSkill_Icon_Equip_C">();
	}
	static class UWBP_Menu_NzSkill_Icon_Equip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_NzSkill_Icon_Equip_C>();
	}
};
static_assert(alignof(UWBP_Menu_NzSkill_Icon_Equip_C) == 0x000008, "Wrong alignment on UWBP_Menu_NzSkill_Icon_Equip_C");
static_assert(sizeof(UWBP_Menu_NzSkill_Icon_Equip_C) == 0x000300, "Wrong size on UWBP_Menu_NzSkill_Icon_Equip_C");
static_assert(offsetof(UWBP_Menu_NzSkill_Icon_Equip_C, Icon_Equip) == 0x0002F8, "Member 'UWBP_Menu_NzSkill_Icon_Equip_C::Icon_Equip' has a wrong offset!");

}

