#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Title_StartUp_UELogo

#include "Basic.hpp"

#include "WBP_Title_StartUp_UELogo_classes.hpp"
#include "WBP_Title_StartUp_UELogo_parameters.hpp"


namespace SDK
{

// Function WBP_Title_StartUp_UELogo.WBP_Title_StartUp_UELogo_C.isFinish
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    isFinish_0                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWBP_Title_StartUp_UELogo_C::isFinish(bool* isFinish_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Title_StartUp_UELogo_C", "isFinish");

	Params::WBP_Title_StartUp_UELogo_C_isFinish Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (isFinish_0 != nullptr)
		*isFinish_0 = Parms.isFinish_0;
}

}

