#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_WMap_BusStop_Guide

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_WMap_BusStop_Guide.WBP_Menu_WMap_BusStop_Guide_C
// 0x0010 (0x0310 - 0x0300)
class UWBP_Menu_WMap_BusStop_Guide_C final : public URCUiMenuBusStopGuide
{
public:
	class UImage*                                 Img_BusStop_Guide_Base;                            // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ButtonGuide_C*                     WBP_ButtonGuide;                                   // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_WMap_BusStop_Guide_C">();
	}
	static class UWBP_Menu_WMap_BusStop_Guide_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_WMap_BusStop_Guide_C>();
	}
};
static_assert(alignof(UWBP_Menu_WMap_BusStop_Guide_C) == 0x000008, "Wrong alignment on UWBP_Menu_WMap_BusStop_Guide_C");
static_assert(sizeof(UWBP_Menu_WMap_BusStop_Guide_C) == 0x000310, "Wrong size on UWBP_Menu_WMap_BusStop_Guide_C");
static_assert(offsetof(UWBP_Menu_WMap_BusStop_Guide_C, Img_BusStop_Guide_Base) == 0x000300, "Member 'UWBP_Menu_WMap_BusStop_Guide_C::Img_BusStop_Guide_Base' has a wrong offset!");
static_assert(offsetof(UWBP_Menu_WMap_BusStop_Guide_C, WBP_ButtonGuide) == 0x000308, "Member 'UWBP_Menu_WMap_BusStop_Guide_C::WBP_ButtonGuide' has a wrong offset!");

}

