#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReSelectEye_Bar

#include "Basic.hpp"

#include "WBP_ReSelectEye_Bar_classes.hpp"
#include "WBP_ReSelectEye_Bar_parameters.hpp"


namespace SDK
{

// Function WBP_ReSelectEye_Bar.WBP_ReSelectEye_Bar_C.ExecuteUbergraph_WBP_ReSelectEye_Bar
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReSelectEye_Bar_C::ExecuteUbergraph_WBP_ReSelectEye_Bar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEye_Bar_C", "ExecuteUbergraph_WBP_ReSelectEye_Bar");

	Params::WBP_ReSelectEye_Bar_C_ExecuteUbergraph_WBP_ReSelectEye_Bar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReSelectEye_Bar.WBP_ReSelectEye_Bar_C.OnChangeNormal
// (Event, Public, BlueprintEvent)

void UWBP_ReSelectEye_Bar_C::OnChangeNormal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEye_Bar_C", "OnChangeNormal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReSelectEye_Bar.WBP_ReSelectEye_Bar_C.OnChangeDisable
// (Event, Public, BlueprintEvent)

void UWBP_ReSelectEye_Bar_C::OnChangeDisable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEye_Bar_C", "OnChangeDisable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReSelectEye_Bar.WBP_ReSelectEye_Bar_C.OnChangeDecide
// (Event, Public, BlueprintEvent)

void UWBP_ReSelectEye_Bar_C::OnChangeDecide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEye_Bar_C", "OnChangeDecide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReSelectEye_Bar.WBP_ReSelectEye_Bar_C.OnChangeSelect
// (Event, Public, BlueprintEvent)

void UWBP_ReSelectEye_Bar_C::OnChangeSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEye_Bar_C", "OnChangeSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReSelectEye_Bar.WBP_ReSelectEye_Bar_C.OnShowStarted
// (Event, Public, BlueprintEvent)

void UWBP_ReSelectEye_Bar_C::OnShowStarted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReSelectEye_Bar_C", "OnShowStarted");

	UObject::ProcessEvent(Func, nullptr);
}

}

