#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_Chara_Sele_Lay_004

#include "Basic.hpp"

#include "WBP_Menu_Chara_Sele_Lay_004_classes.hpp"
#include "WBP_Menu_Chara_Sele_Lay_004_parameters.hpp"


namespace SDK
{

// Function WBP_Menu_Chara_Sele_Lay_004.WBP_Menu_Chara_Sele_Lay_004_C.ButtonNavigation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Menu_Chara_Sele_Lay_004_C::ButtonNavigation(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Menu_Chara_Sele_Lay_004_C", "ButtonNavigation");

	Params::WBP_Menu_Chara_Sele_Lay_004_C_ButtonNavigation Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

