#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Menu_SvLd_List

#include "Basic.hpp"

#include "RC_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Menu_SvLd_List.WBP_Menu_SvLd_List_C
// 0x0000 (0x03E8 - 0x03E8)
class UWBP_Menu_SvLd_List_C final : public URCSaveLoadList
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Menu_SvLd_List_C">();
	}
	static class UWBP_Menu_SvLd_List_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Menu_SvLd_List_C>();
	}
};
static_assert(alignof(UWBP_Menu_SvLd_List_C) == 0x000008, "Wrong alignment on UWBP_Menu_SvLd_List_C");
static_assert(sizeof(UWBP_Menu_SvLd_List_C) == 0x0003E8, "Wrong size on UWBP_Menu_SvLd_List_C");

}

