#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Zero0_0030_M0000_EVENT_000

#include "Basic.hpp"

#include "Zero0_0030_M0000_EVENT_000_classes.hpp"
#include "Zero0_0030_M0000_EVENT_000_parameters.hpp"


namespace SDK
{

// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.ExecuteUbergraph_00_0030_M0000_EVENT_000
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::ExecuteUbergraph_00_0030_M0000_EVENT_000(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "ExecuteUbergraph_00_0030_M0000_EVENT_000");

	Params::Zero0_0030_M0000_EVENT_000_C_ExecuteUbergraph_00_0030_M0000_EVENT_000 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.EventSkip
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::EventSkip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "EventSkip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.EventLoadEnd
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::EventLoadEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "EventLoadEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.Event_000
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::Event_000()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "Event_000");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkEnd
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.EventEnd
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::EventEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "EventEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.EventStart
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::EventStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "EventStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "ReceiveTick");

	Params::Zero0_0030_M0000_EVENT_000_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetAtoB
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkSetAtoB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetAtoB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetA2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetA2(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetA2");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetA2 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetA1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetA1(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetA1");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetA1 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetBtoC
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkSetBtoC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetBtoC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetB1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetB1(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetB1");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetB1 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetCtoD
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkSetCtoD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetCtoD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetC2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetC2(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetC2");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetC2 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetC1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetC1(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetC1");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetC1 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetDtoE
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkSetDtoE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetDtoE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetD1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetD1(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetD1");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetD1 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetEtoF
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkSetEtoF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetEtoF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetE1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetE1(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetE1");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetE1 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetToFinish
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkSetToFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetToFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.AllTalkFinish
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::AllTalkFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "AllTalkFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkStart
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::TalkStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.CustomEvent_3
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::CustomEvent_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "CustomEvent_3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.TalkSetF1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TalkIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AZero0_0030_M0000_EVENT_000_C::TalkSetF1(int32 TalkIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "TalkSetF1");

	Params::Zero0_0030_M0000_EVENT_000_C_TalkSetF1 Parms{};

	Parms.TalkIndex = TalkIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.SE_DropBookHeadThenGround
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::SE_DropBookHeadThenGround()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "SE_DropBookHeadThenGround");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.ENV_SoundStart
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::ENV_SoundStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "ENV_SoundStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.SoundStart
// (BlueprintCallable, BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::SoundStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "SoundStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.時計を探す__UpdateFunc
// (BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::m________________UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "時計を探す__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function 00_0030_M0000_EVENT_000.00_0030_M0000_EVENT_000_C.時計を探す__FinishedFunc
// (BlueprintEvent)

void AZero0_0030_M0000_EVENT_000_C::m________________FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("00_0030_M0000_EVENT_000_C", "時計を探す__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

